"""Part sourcing: distributors + CAD attach + body/pin gates.

Distributors (LCSC, later DigiKey/Mouser) give MPN/stock. CAD libraries give
symbols/footprints. Datasheet body size is the gate — a land that exists is
not automatically the right land.
"""

from __future__ import annotations

import json
import os
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from .eda import fetch_easyeda, group_pins, parse_symbol, pin_kind
from .geom import box_size_mm, footprint_box_local, footprint_pad_count
from .lcsc import LcscHit, search_lcsc

_BODY = re.compile(
    r"(\d+(?:\.\d+)?)\s*[xX×]\s*(\d+(?:\.\d+)?)",
)
_GENERIC_PKG = re.compile(r"^(0[1248]0[125]|0603|0805|1206)$")
_ZEN_FILE = re.compile(r'footprint\s*=\s*File\(\s*"([^"]+)"\s*\)')
_ZEN_MPN = re.compile(r'Part\(\s*mpn\s*=\s*"([^"]+)"')
_ZEN_MFR = re.compile(r'manufacturer\s*=\s*"([^"]+)"')


def parse_body_mm(text: str | None) -> tuple[float, float] | None:
    """Pull L×W millimetres out of a package string or `--body 1.5x1.5`."""
    if not text:
        return None
    m = _BODY.search(str(text).replace("mm", ""))
    if not m:
        return None
    return (float(m.group(1)), float(m.group(2)))


def guess_kind(query: str, package: str = "") -> str:
    q = query.lower()
    pkg = package.replace(" ", "")
    if _GENERIC_PKG.match(pkg) or re.search(r"\b(0402|0603|0805|1206)\b", q):
        if re.search(r"\d+\s*(nf|uf|pf|kohm|ohm|k\b|r\b)", q):
            return "generic"
        if re.search(r"\b(cap|resistor|mlcc)\b", q):
            return "generic"
    return "ic"


@dataclass
class SourceRecord:
    mpn: str
    manufacturer: str = ""
    kind: str = "ic"
    package: str = ""
    body_mm: tuple[float, float] | None = None
    lcsc: str | None = None
    jlc_basic: bool | None = None
    stock: int | None = None
    datasheet: str | None = None
    footprint: str | None = None
    symbol: str | None = None
    cad_origin: str = "none"
    status: str = "needs_human"
    gates: dict = field(default_factory=dict)
    vendors: list[dict] = field(default_factory=list)
    pins: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "mpn": self.mpn,
            "manufacturer": self.manufacturer,
            "kind": self.kind,
            "package": self.package,
            "body_mm": list(self.body_mm) if self.body_mm else None,
            "lcsc": self.lcsc,
            "jlc_basic": self.jlc_basic,
            "stock": self.stock,
            "datasheet": self.datasheet,
            "footprint": self.footprint,
            "symbol": self.symbol,
            "cad_origin": self.cad_origin,
            "status": self.status,
            "gates": self.gates,
            "vendors": self.vendors,
            "pins": self.pins,
        }


def skipped_western() -> list[dict]:
    skipped = []
    if not os.environ.get("DIGIKEY_CLIENT_ID"):
        skipped.append({"vendor": "digikey", "reason": "DIGIKEY_CLIENT_ID not set"})
    if not os.environ.get("MOUSER_API_KEY"):
        skipped.append({"vendor": "mouser", "reason": "MOUSER_API_KEY not set"})
    return skipped


def search_parts(query: str, *, fab: str = "jlcpcb", limit: int = 10, opener=None) -> dict:
    hits: list[LcscHit] = []
    errors: list[str] = []
    try:
        hits = search_lcsc(query, limit=limit, opener=opener)
    except RuntimeError as e:
        errors.append(str(e))
    rows = [h.to_dict() for h in hits]
    if fab == "jlcpcb":
        rows.sort(key=lambda r: (not r.get("jlc_basic"), -(r.get("stock") or 0)))
    return {
        "query": query,
        "fab": fab,
        "hits": rows,
        "skipped": skipped_western(),
        "errors": errors,
    }


def _slug(s: str) -> str:
    out = "".join(ch if ch.isalnum() or ch in "_-" else "_" for ch in s).strip("_")
    return out or "part"


def write_package(record: SourceRecord, dest: Path) -> Path:
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "SOURCE.json").write_text(json.dumps(record.to_dict(), indent=2) + "\n")
    if record.kind == "generic":
        (dest / "part.zen").write_text(_generic_zen(record))
    else:
        (dest / f"{_slug(record.mpn)}.zen").write_text(_ic_zen(record))
    return dest


def _generic_zen(r: SourceRecord) -> str:
    mfr = r.manufacturer or "unknown"
    extra = f', manufacturer = "{mfr}"'
    return (
        f"# Generated by pcb-space source. Attach to a stdlib generic.\n"
        f"# Do not download a unique 0402 symbol for this MPN.\n"
        f"# Capacitor(..., part = Part(mpn = \"{r.mpn}\"{extra}))\n"
        f"# Resistor(..., part = Part(mpn = \"{r.mpn}\"{extra}))\n"
        f"# package = \"{r.package}\"\n"
        f"# lcsc = \"{r.lcsc or ''}\"\n"
    )


def _ic_zen(r: SourceRecord) -> str:
    fp = r.footprint or "MISSING.kicad_mod"
    name = _slug(r.mpn).replace("-", "_")
    mfr = r.manufacturer or "unknown"
    ds = f'\n    datasheet = "{r.datasheet}",' if r.datasheet else ""
    grouped = r.pins or {}
    ios = []
    pin_map = []
    definition = []
    for pname, pads in grouped.items():
        kind = pin_kind(pname)
        optional = ", optional=True" if kind == "Net" else ""
        ios.append(f'{pname} = io({kind}(){optional})')
        pad_list = ", ".join(f'"{p}"' for p in pads)
        definition.append(f'            ("{pname}", [{pad_list}]),')
        pin_map.append(f'        "{pname}": {pname},')
    if not grouped:
        ios.append("# no pins parsed — fill from datasheet")
        definition.append('            # ("PIN", ["1"]),')
    io_block = "\n".join(ios)
    def_block = "\n".join(definition) if definition else ""
    pins_block = "\n".join(pin_map) if pin_map else ""
    return (
        f'"""Sourced by pcb-space. Pin names come from the CAD library,\n'
        f"not a datasheet lock — check SOURCE.json gates before trusting.\n"
        f'LCSC {r.lcsc or ""} / {r.package}\n"""\n\n'
        f"{io_block}\n\n"
        f"Component(\n"
        f'    name = "{name}",\n'
        f'    footprint = File("{Path(fp).name}"),\n'
        f'    symbol = Symbol(\n'
        f'        name = "{name}",\n'
        f"        definition = [\n"
        f"{def_block}\n"
        f"        ],\n"
        f"    ),\n"
        f'    part = Part(mpn = "{r.mpn}", manufacturer = "{mfr}"),{ds}\n'
        f"    pins = {{\n"
        f"{pins_block}\n"
        f"    }},\n"
        f")\n"
    )


def _attach_symbol(rec: SourceRecord, pkg: Path) -> None:
    cad = fetch_easyeda(rec.lcsc, pkg / "_easyeda")
    sym_src = Path(cad["symbol"])
    sym_dst = pkg / f"{_slug(rec.mpn)}.kicad_sym"
    shutil.copy2(sym_src, sym_dst)
    rec.symbol = sym_dst.name
    parsed = parse_symbol(sym_dst)
    rec.pins = group_pins(parsed["pins"])
    rec.datasheet = rec.datasheet or parsed.get("datasheet") or None
    if not rec.manufacturer:
        rec.manufacturer = parsed.get("manufacturer") or ""
    rec.gates["pins"] = len(parsed["pins"])
    rec.gates["pin_names"] = sorted(rec.pins)
    shutil.rmtree(pkg / "_easyeda", ignore_errors=True)


def import_part(
    query: str,
    dest: Path,
    *,
    kind: str = "auto",
    footprint: Path | None = None,
    body: str | None = None,
    manufacturer: str = "",
    fab: str = "jlcpcb",
    opener=None,
    fetch_cad: bool = True,
) -> dict:
    found = search_parts(query, fab=fab, limit=5, opener=opener)
    hit = found["hits"][0] if found["hits"] else {}
    mpn = hit.get("mpn") or query
    package = hit.get("package") or ""
    kind_u = kind if kind != "auto" else guess_kind(query, package)
    body_mm = parse_body_mm(body) or parse_body_mm(package)
    rec = SourceRecord(
        mpn=mpn,
        manufacturer=manufacturer,
        kind=kind_u,
        package=package,
        body_mm=body_mm,
        lcsc=hit.get("lcsc"),
        jlc_basic=hit.get("jlc_basic"),
        stock=hit.get("stock"),
        vendors=found["hits"],
        cad_origin="none",
        status="needs_human",
    )
    dest = Path(dest)
    pkg = dest / _slug(rec.manufacturer or "vendor") / _slug(rec.mpn)
    if footprint:
        footprint = Path(footprint)
        pkg.mkdir(parents=True, exist_ok=True)
        copied = pkg / footprint.name
        shutil.copy2(footprint, copied)
        rec.footprint = copied.name
        rec.cad_origin = "kicad-lib"
        rec.gates = check_footprint(copied, body_mm=rec.body_mm)
        rec.status = "ok" if rec.gates.get("ok") else "gate_failed"
        if fetch_cad and rec.lcsc:
            try:
                _attach_symbol(rec, pkg)
                rec.cad_origin = "kicad-lib+easyeda-symbol"
            except RuntimeError as e:
                rec.gates["symbol_note"] = str(e)
    elif kind_u == "generic":
        rec.cad_origin = "stdlib-generic"
        rec.status = "ok"
        rec.gates = {"ok": True, "note": "generic: no unique CAD"}
    elif fetch_cad and rec.lcsc:
        pkg.mkdir(parents=True, exist_ok=True)
        try:
            cad = fetch_easyeda(rec.lcsc, pkg / "_easyeda")
            fp_src = Path(cad["footprint"])
            sym_src = Path(cad["symbol"])
            fp_dst = pkg / fp_src.name
            sym_dst = pkg / f"{_slug(rec.mpn)}.kicad_sym"
            shutil.copy2(fp_src, fp_dst)
            shutil.copy2(sym_src, sym_dst)
            rec.footprint = fp_dst.name
            rec.symbol = sym_dst.name
            rec.cad_origin = "easyeda"
            parsed = parse_symbol(sym_dst)
            rec.pins = group_pins(parsed["pins"])
            rec.datasheet = rec.datasheet or parsed.get("datasheet") or None
            if not rec.manufacturer:
                rec.manufacturer = parsed.get("manufacturer") or ""
            rec.gates = check_footprint(fp_dst, body_mm=rec.body_mm)
            rec.gates["pins"] = len(parsed["pins"])
            rec.gates["pin_names"] = sorted(rec.pins)
            rec.status = "ok" if rec.gates.get("ok") or rec.body_mm is None else "gate_failed"
            if rec.body_mm is None and rec.gates.get("pads", 0) > 0:
                rec.gates["ok"] = True
                rec.gates["note"] = "no datasheet body to gate; CAD attached"
                rec.status = "ok"
            shutil.rmtree(pkg / "_easyeda", ignore_errors=True)
        except RuntimeError as e:
            rec.status = "needs_human"
            rec.gates = {"ok": False, "note": str(e)}
    else:
        rec.status = "needs_human"
        rec.gates = {
            "ok": False,
            "note": "no footprint given; pass --footprint or install easyeda2kicad",
        }
    write_package(rec, pkg)
    return {"package": str(pkg), "record": rec.to_dict(), "search": found}


def _load_footprint_text(path: Path) -> tuple[str, Path]:
    path = Path(path)
    if path.is_dir():
        source = path / "SOURCE.json"
        if source.exists():
            rec = json.loads(source.read_text())
            fp = rec.get("footprint")
            if fp:
                fp_path = path / fp
                return fp_path.read_text(), fp_path
        mods = list(path.glob("*.kicad_mod"))
        if mods:
            return mods[0].read_text(), mods[0]
        zens = list(path.glob("*.zen"))
        if zens:
            return _load_footprint_text(zens[0])
        raise FileNotFoundError(f"no footprint in {path}")
    if path.suffix == ".zen":
        text = path.read_text()
        m = _ZEN_FILE.search(text)
        if not m:
            raise FileNotFoundError(f"{path} has no footprint = File(...)")
        fp = (path.parent / m.group(1)).resolve()
        return fp.read_text(), fp
    return path.read_text(), path


def check_footprint(
    path: Path,
    *,
    body_mm: tuple[float, float] | None = None,
    tol_mm: float = 0.2,
) -> dict:
    """Compare footprint Fab/courtyard to a datasheet body. Fail = wrong land."""
    text, used = _load_footprint_text(Path(path))
    fab = footprint_box_local(text, "fab")
    crtyd = footprint_box_local(text, "courtyard")
    fab_wh = box_size_mm(fab)
    crtyd_wh = box_size_mm(crtyd)
    pads = footprint_pad_count(text)
    if body_mm is None:
        source = Path(path)
        if source.is_dir() and (source / "SOURCE.json").exists():
            rec = json.loads((source / "SOURCE.json").read_text())
            if rec.get("body_mm"):
                body_mm = (float(rec["body_mm"][0]), float(rec["body_mm"][1]))
            elif rec.get("package"):
                body_mm = parse_body_mm(rec["package"])
        if body_mm is None:
            body_mm = parse_body_mm(used.stem)
    body_ok = None
    if body_mm is not None:
        w, h = body_mm
        a = abs(fab_wh[0] - w) <= tol_mm and abs(fab_wh[1] - h) <= tol_mm
        b = abs(fab_wh[0] - h) <= tol_mm and abs(fab_wh[1] - w) <= tol_mm
        body_ok = a or b
    ok = True if body_ok is None else body_ok
    return {
        "ok": bool(ok),
        "footprint": str(used),
        "pads": pads,
        "fab_mm": [round(fab_wh[0], 3), round(fab_wh[1], 3)],
        "courtyard_mm": [round(crtyd_wh[0], 3), round(crtyd_wh[1], 3)],
        "datasheet_body_mm": list(body_mm) if body_mm else None,
        "tol_mm": tol_mm,
        "body_ok": body_ok,
        "note": (
            None
            if body_ok is not False
            else (
                f"Fab {fab_wh[0]:.2f}×{fab_wh[1]:.2f} mm vs datasheet "
                f"{body_mm[0]}×{body_mm[1]} mm — wrong land (SHT40-class miss)"
            )
        ),
    }
