"""Part sourcing: distributors + CAD attach + body/pin gates.

Distributors (LCSC, later DigiKey/Mouser) give MPN/stock. CAD libraries give
symbols/footprints. Datasheet body size is the gate — a land that exists is
not automatically the right land.
"""

from __future__ import annotations

import json
import os
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

from .eda import fetch_easyeda, group_pins, parse_symbol, pin_kind
from .geom import box_size_mm, footprint_box_local, footprint_pad_count
from .pins import check_pins, load_pin_lock
from .lcsc import LcscHit, search_lcsc

_BODY = re.compile(
    r"(\d+(?:\.\d+)?)\s*[xX×]\s*(\d+(?:\.\d+)?)",
)
_GENERIC_PKG = re.compile(r"^(0[1248]0[125]|0603|0805|1206)$")
_ZEN_FILE = re.compile(r'footprint\s*=\s*File\(\s*"([^"]+)"\s*\)')
_ZEN_MPN = re.compile(r'Part\(\s*mpn\s*=\s*"([^"]+)"')
_ZEN_MFR = re.compile(r'manufacturer\s*=\s*"([^"]+)"')


def parse_body_mm(text: str | None) -> tuple[float, float] | None:
    """Pull L×W millimetres out of a package string or `--body 1.5x1.5`."""
    if not text:
        return None
    m = _BODY.search(str(text).replace("mm", ""))
    if not m:
        return None
    return (float(m.group(1)), float(m.group(2)))


def guess_kind(query: str, package: str = "") -> str:
    q = query.lower()
    pkg = package.replace(" ", "")
    if _GENERIC_PKG.match(pkg) or re.search(r"\b(0402|0603|0805|1206)\b", q):
        if re.search(r"\d+\s*(nf|uf|pf|kohm|ohm|k\b|r\b)", q):
            return "generic"
        if re.search(r"\b(cap|resistor|mlcc)\b", q):
            return "generic"
    return "ic"


@dataclass
class SourceRecord:
    mpn: str
    manufacturer: str = ""
    kind: str = "ic"
    package: str = ""
    body_mm: tuple[float, float] | None = None
    lcsc: str | None = None
    jlc_basic: bool | None = None
    stock: int | None = None
    datasheet: str | None = None
    footprint: str | None = None
    symbol: str | None = None
    cad_origin: str = "none"
    status: str = "needs_human"
    gates: dict = field(default_factory=dict)
    vendors: list[dict] = field(default_factory=list)
    pins: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "mpn": self.mpn,
            "manufacturer": self.manufacturer,
            "kind": self.kind,
            "package": self.package,
            "body_mm": list(self.body_mm) if self.body_mm else None,
            "lcsc": self.lcsc,
            "jlc_basic": self.jlc_basic,
            "stock": self.stock,
            "datasheet": self.datasheet,
            "footprint": self.footprint,
            "symbol": self.symbol,
            "cad_origin": self.cad_origin,
            "status": self.status,
            "gates": self.gates,
            "vendors": self.vendors,
            "pins": self.pins,
        }


def skipped_western() -> list[dict]:
    skipped = []
    if not os.environ.get("DIGIKEY_CLIENT_ID"):
        skipped.append({"vendor": "digikey", "reason": "DIGIKEY_CLIENT_ID not set"})
    if not os.environ.get("MOUSER_API_KEY"):
        skipped.append({"vendor": "mouser", "reason": "MOUSER_API_KEY not set"})
    return skipped


def search_parts(query: str, *, fab: str = "jlcpcb", limit: int = 10, opener=None) -> dict:
    hits: list[LcscHit] = []
    errors: list[str] = []
    try:
        hits = search_lcsc(query, limit=limit, opener=opener)
    except RuntimeError as e:
        errors.append(str(e))
    rows = [h.to_dict() for h in hits]
    if fab == "jlcpcb":
        rows.sort(key=lambda r: (not r.get("jlc_basic"), -(r.get("stock") or 0)))
    return {
        "query": query,
        "fab": fab,
        "hits": rows,
        "skipped": skipped_western(),
        "errors": errors,
    }


def _slug(s: str) -> str:
    out = "".join(ch if ch.isalnum() or ch in "_-" else "_" for ch in s).strip("_")
    return out or "part"


def write_package(record: SourceRecord, dest: Path) -> Path:
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "SOURCE.json").write_text(json.dumps(record.to_dict(), indent=2) + "\n")
    if record.kind == "generic":
        (dest / "part.zen").write_text(_generic_zen(record))
    else:
        (dest / f"{_slug(record.mpn)}.zen").write_text(_ic_zen(record))
    return dest


def _generic_zen(r: SourceRecord) -> str:
    mfr = r.manufacturer or "unknown"
    extra = f', manufacturer = "{mfr}"'
    return (
        f"# Generated by pcb-space source. Attach to a stdlib generic.\n"
        f"# Do not download a unique 0402 symbol for this MPN.\n"
        f"# Capacitor(..., part = Part(mpn = \"{r.mpn}\"{extra}))\n"
        f"# Resistor(..., part = Part(mpn = \"{r.mpn}\"{extra}))\n"
        f"# package = \"{r.package}\"\n"
        f"# lcsc = \"{r.lcsc or ''}\"\n"
    )


def _ic_zen(r: SourceRecord) -> str:
    fp = r.footprint or "MISSING.kicad_mod"
    name = _slug(r.mpn).replace("-", "_")
    mfr = r.manufacturer or "unknown"
    ds = f'\n    datasheet = "{r.datasheet}",' if r.datasheet else ""
    grouped = r.pins or {}
    ios = []
    pin_map = []
    definition = []
    for pname, pads in grouped.items():
        kind = pin_kind(pname)
        optional = ", optional=True" if kind == "Net" else ""
        ios.append(f'{pname} = io({kind}(){optional})')
        pad_list = ", ".join(f'"{p}"' for p in pads)
        definition.append(f'            ("{pname}", [{pad_list}]),')
        pin_map.append(f'        "{pname}": {pname},')
    if not grouped:
        ios.append("# no pins parsed — fill from datasheet")
        definition.append('            # ("PIN", ["1"]),')
    io_block = "\n".join(ios)
    def_block = "\n".join(definition) if definition else ""
    pins_block = "\n".join(pin_map) if pin_map else ""
    return (
        f'"""Sourced by pcb-space. Pin names are this .zen definition;\n'
        f"graphics from .kicad_sym (pad numbers). LCSC {r.lcsc or ''} / {r.package}\n"
        f'"""\n\n'
        f"{io_block}\n\n"
        f"Component(\n"
        f'    name = "{name}",\n'
        f'    footprint = File("{Path(fp).name}"),\n'
        f'    symbol = Symbol(\n'
        f'        name = "{name}",\n'
        f"        definition = [\n"
        f"{def_block}\n"
        f"        ],\n"
        f"    ),\n"
        f'    part = Part(mpn = "{r.mpn}", manufacturer = "{mfr}"),{ds}\n'
        f"    pins = {{\n"
        f"{pins_block}\n"
        f"    }},\n"
        f")\n"
    )


def select_hit(query: str, hits: list[dict], pick: str | None = None) -> dict | None:
    """Return one LCSC row only when the query (or --pick) names it uniquely."""
    if not hits:
        return None
    if pick:
        p = str(pick).strip().upper()
        p_num = p[1:] if p.startswith("C") and p[1:].isdigit() else p
        matched = []
        for h in hits:
            lcsc = str(h.get("lcsc") or "").upper()
            mpn = str(h.get("mpn") or "").upper()
            if lcsc == p or mpn == p or lcsc.lstrip("C") == p_num:
                matched.append(h)
        return matched[0] if len(matched) == 1 else None
    q = query.strip().upper()
    if q.startswith("C") and q[1:].isdigit():
        exact = [h for h in hits if str(h.get("lcsc") or "").upper() == q]
        if len(exact) == 1:
            return exact[0]
    exact_mpn = [h for h in hits if str(h.get("mpn") or "").upper() == q]
    if len(exact_mpn) == 1:
        return exact_mpn[0]
    if len(hits) == 1:
        return hits[0]
    return None


def _attach_symbol(rec: SourceRecord, pkg: Path) -> None:
    cad = fetch_easyeda(rec.lcsc, pkg / "_easyeda")
    sym_src = Path(cad["symbol"])
    sym_dst = pkg / f"{_slug(rec.mpn)}.kicad_sym"
    shutil.copy2(sym_src, sym_dst)
    rec.symbol = sym_dst.name
    parsed = parse_symbol(sym_dst)
    rec.pins = group_pins(parsed["pins"])
    rec.datasheet = rec.datasheet or parsed.get("datasheet") or None
    if not rec.manufacturer:
        rec.manufacturer = parsed.get("manufacturer") or ""
    rec.gates["pins"] = len(parsed["pins"])
    rec.gates["pin_names"] = sorted(rec.pins)
    shutil.rmtree(pkg / "_easyeda", ignore_errors=True)


def import_part(
    query: str,
    dest: Path,
    *,
    kind: str = "auto",
    footprint: Path | None = None,
    body: str | None = None,
    manufacturer: str = "",
    fab: str = "jlcpcb",
    opener=None,
    pick: str | None = None,
    easyeda: bool = False,
    pins: Path | dict | None = None,
) -> dict:
    """Attach one LCSC row. EasyEDA is opt-in and never the pin authority.

    ICs are status=ok only with a chosen land (--footprint or --easyeda) and a
    datasheet pin table (--pins). Multiple search hits with no --pick → status
    pick (nothing written).
    """
    found = search_parts(query, fab=fab, limit=8, opener=opener)
    hits = found.get("hits") or []
    kind_guess = kind if kind != "auto" else guess_kind(query, (hits[0].get("package") if hits else "") or "")
    if kind_guess != "generic":
        hit = select_hit(query, hits, pick=pick)
        if hit is None:
            rec = SourceRecord(
                mpn=query,
                kind="ic",
                vendors=hits,
                status="pick",
                gates={
                    "ok": False,
                    "note": "multiple LCSC hits; pass --pick C… (or a unique MPN). EasyEDA was not attached.",
                },
            )
            return {"package": None, "record": rec.to_dict(), "search": found}
    else:
        hit = select_hit(query, hits, pick=pick) or (hits[0] if hits else {})

    mpn = (hit or {}).get("mpn") or query
    package = (hit or {}).get("package") or ""
    kind_u = kind if kind != "auto" else guess_kind(query, package)
    body_mm = parse_body_mm(body) or parse_body_mm(package)
    rec = SourceRecord(
        mpn=mpn,
        manufacturer=manufacturer,
        kind=kind_u,
        package=package,
        body_mm=body_mm,
        lcsc=(hit or {}).get("lcsc"),
        jlc_basic=(hit or {}).get("jlc_basic"),
        stock=(hit or {}).get("stock"),
        vendors=hits,
        cad_origin="none",
        status="needs_human",
    )
    dest = Path(dest)
    pkg = dest / _slug(rec.manufacturer or "vendor") / _slug(rec.mpn)
    lock = None
    if isinstance(pins, dict):
        lock = {str(k): list(v) if not isinstance(v, str) else [v] for k, v in pins.items()}
    elif pins is not None:
        lock = load_pin_lock(Path(pins))

    if kind_u == "generic":
        rec.cad_origin = "stdlib-generic"
        rec.status = "ok"
        rec.gates = {"ok": True, "note": "generic: no unique CAD"}
        write_package(rec, pkg)
        return {"package": str(pkg), "record": rec.to_dict(), "search": found}

    pkg.mkdir(parents=True, exist_ok=True)
    if footprint:
        footprint = Path(footprint)
        copied = pkg / footprint.name
        if footprint.resolve() != copied.resolve():
            shutil.copy2(footprint, copied)
        rec.footprint = copied.name
        rec.cad_origin = "kicad-lib"
        rec.gates = check_footprint(copied, body_mm=rec.body_mm)
    elif easyeda and rec.lcsc:
        try:
            cad = fetch_easyeda(rec.lcsc, pkg / "_easyeda")
            fp_src = Path(cad["footprint"])
            sym_src = Path(cad["symbol"])
            fp_dst = pkg / fp_src.name
            shutil.copy2(fp_src, fp_dst)
            shutil.copy2(sym_src, pkg / f"{_slug(rec.mpn)}.kicad_sym")
            rec.footprint = fp_dst.name
            rec.symbol = f"{_slug(rec.mpn)}.kicad_sym"
            rec.cad_origin = "easyeda"
            parsed = parse_symbol(pkg / rec.symbol)
            rec.datasheet = rec.datasheet or parsed.get("datasheet") or None
            if not rec.manufacturer:
                rec.manufacturer = parsed.get("manufacturer") or ""
            rec.gates = check_footprint(fp_dst, body_mm=rec.body_mm)
            rec.gates["easyeda_pin_names"] = sorted(group_pins(parsed["pins"]))
            shutil.rmtree(pkg / "_easyeda", ignore_errors=True)
        except RuntimeError as e:
            rec.status = "needs_human"
            rec.gates = {"ok": False, "note": str(e)}
            write_package(rec, pkg)
            return {"package": str(pkg), "record": rec.to_dict(), "search": found}
    else:
        rec.status = "needs_human"
        rec.gates = {
            "ok": False,
            "note": "IC: pass --footprint PATH (KiCad land) or --easyeda (candidate land). "
            "Pass --pins JSON only to fill the .zen definition. EasyEDA is not autoselected.",
        }
        write_package(rec, pkg)
        return {"package": str(pkg), "record": rec.to_dict(), "search": found}

    if rec.gates.get("ok") is False and rec.body_mm is not None:
        rec.status = "gate_failed"
        write_package(rec, pkg)
        return {"package": str(pkg), "record": rec.to_dict(), "search": found}

    if lock:
        rec.pins = lock
    elif rec.symbol:
        rec.pins = group_pins(parse_symbol(pkg / rec.symbol)["pins"])
    if rec.pins:
        rec.status = "ok"
        rec.gates["ok"] = True
        rec.gates["pin_ok"] = True
        if rec.symbol:
            pin_rep = check_pins(pkg, pins=rec.pins)
            rec.gates["pin_ok"] = pin_rep.get("pin_ok")
            rec.gates["pin_mismatches"] = pin_rep.get("mismatches") or []
            if pin_rep.get("pin_ok") is False:
                rec.status = "gate_failed"
                rec.gates["ok"] = False
                rec.gates["note"] = pin_rep.get("note")
                write_package(rec, pkg)
                return {"package": str(pkg), "record": rec.to_dict(), "search": found}
    else:
        rec.status = "needs_pin_lock"
        rec.gates["ok"] = False
        rec.gates["pin_ok"] = None
        rec.gates["note"] = (
            (rec.gates.get("note") or "")
            + "; land attached; add a .zen definition (or --pins JSON to generate one)"
        ).strip("; ")

    write_package(rec, pkg)
    return {"package": str(pkg), "record": rec.to_dict(), "search": found}


def _load_footprint_text(path: Path) -> tuple[str, Path]:
    path = Path(path)
    if path.is_dir():
        source = path / "SOURCE.json"
        if source.exists():
            rec = json.loads(source.read_text())
            fp = rec.get("footprint")
            if fp:
                fp_path = path / fp
                return fp_path.read_text(), fp_path
        mods = list(path.glob("*.kicad_mod"))
        if mods:
            return mods[0].read_text(), mods[0]
        zens = list(path.glob("*.zen"))
        if zens:
            return _load_footprint_text(zens[0])
        raise FileNotFoundError(f"no footprint in {path}")
    if path.suffix == ".zen":
        text = path.read_text()
        m = _ZEN_FILE.search(text)
        if not m:
            raise FileNotFoundError(f"{path} has no footprint = File(...)")
        fp = (path.parent / m.group(1)).resolve()
        return fp.read_text(), fp
    return path.read_text(), path


def check_footprint(
    path: Path,
    *,
    body_mm: tuple[float, float] | None = None,
    tol_mm: float = 0.2,
) -> dict:
    """Compare footprint Fab/courtyard to a datasheet body. Fail = wrong land."""
    text, used = _load_footprint_text(Path(path))
    fab = footprint_box_local(text, "fab")
    crtyd = footprint_box_local(text, "courtyard")
    fab_wh = box_size_mm(fab)
    crtyd_wh = box_size_mm(crtyd)
    pads = footprint_pad_count(text)
    if body_mm is None:
        source = Path(path)
        if source.is_dir() and (source / "SOURCE.json").exists():
            rec = json.loads((source / "SOURCE.json").read_text())
            if rec.get("body_mm"):
                body_mm = (float(rec["body_mm"][0]), float(rec["body_mm"][1]))
            elif rec.get("package"):
                body_mm = parse_body_mm(rec["package"])
        if body_mm is None:
            body_mm = parse_body_mm(used.stem)
    body_ok = None
    if body_mm is not None:
        w, h = body_mm
        a = abs(fab_wh[0] - w) <= tol_mm and abs(fab_wh[1] - h) <= tol_mm
        b = abs(fab_wh[0] - h) <= tol_mm and abs(fab_wh[1] - w) <= tol_mm
        body_ok = a or b
    ok = True if body_ok is None else body_ok
    note = (
        None
        if body_ok is not False
        else (
            f"Fab {fab_wh[0]:.2f}×{fab_wh[1]:.2f} mm vs datasheet "
            f"{body_mm[0]}×{body_mm[1]} mm — wrong land (SHT40-class miss)"
        )
    )
    pin_report: dict = {}
    pkg = Path(path)
    if pkg.is_file():
        pkg = pkg.parent
    if pkg.is_dir() and (list(pkg.glob("*.zen")) or (pkg / "SOURCE.json").exists()):
        pin_report = check_pins(pkg)
        if pin_report.get("pin_ok") is False:
            ok = False
            extra = pin_report.get("note") or "pin-lock mismatch"
            note = f"{note}; {extra}" if note else extra
    return {
        "ok": bool(ok),
        "footprint": str(used),
        "pads": pads,
        "fab_mm": [round(fab_wh[0], 3), round(fab_wh[1], 3)],
        "courtyard_mm": [round(crtyd_wh[0], 3), round(crtyd_wh[1], 3)],
        "datasheet_body_mm": list(body_mm) if body_mm else None,
        "tol_mm": tol_mm,
        "body_ok": body_ok,
        "pin_ok": pin_report.get("pin_ok"),
        "pin_mismatches": pin_report.get("mismatches") or [],
        "note": note,
    }
